option_descriptor = {
'AH':'Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals, & Metallic Rod Scraper','BR':'Bumper Rear', 'BF':'Bumper Front',
'BB':'Bumper Front & Bumper Rear','BD':'Bumper Front, Bumper Rear, Viton & Metallic Rod Scraper',
'BE':'Bumper Front, Bumper Rear, Stainless Steel Piston Rod & SS Tie Rods & Metallic Rod Scraper',
'BG':'Bumper Front, Bumper Rear, Stainless Steel Piston Rod & SS Tie Rods, Viton Seals & Metallic Rod Scraper',
'BI':'Bumper Front, Bumper Rear, Male Rod & Metallic Rod Scraper','BJ':'Bumper Front, Bumper Rear, Male Rod, Viton Seals & Metallic Rod Scraper',
'BL':'Bumpers, Head and Cap and Low Breakaway','BM':'Bumper Front, Bumper Rear, & Male Rod Stud', 'BN':'Bumper Front, Bumper Rear, Male Rod, Stainless Steel Piston Rod & SS Tie Rods',
'BO':'Bumper Front, Bumper Rear, Male Rod, Stainless Steel Piston Rod & SS Tie Rods, & Metallic Rod Scraper','BP':'Bumper Front, Bumper Rear, & PolyPak Rod Seal',
'BQ':'Bumper Front, Bumper Rear, Male Rod, Stainless Steel Piston Rod & SS Tie Rods & Viton Seals',
'BS':'Bumper Front, Bumper Rear, Stainless Steel Piston Rod, & Stainless Steel Tie Rods',
'BT':'Bumper Front, Bumper Rear, & Stainless Steel Tie Rods', 'BU':'Bumper Front, Bumper Rear, Male Rod, Stainless Steel Piston Rod & SS Tie Rods, Viton Seals & Metallic Rod Scraper',
'BV':'Bumper Front, Bumper Rear, & Viton','BW':'Bumper Front, Bumper Rear & Metallic Rod Scraper','CD':'Double Rod and Bumper (Cap End Only)',
'CE':'Composite Tubing and Silent Seal Bumpers','CR':'Composite Cylinder Tube & Stainless Steel Piston Rod','CS':'Composite Cylinder Tube & Stainless Steel Tie Rods',
'CU':'Composite Cylinder Tube, Stainless Steel Piston Rod, & Stainless Steel Tie Rods','DB':'Double Rod and Bumpers (Head and Cap)',
'DC':'Double Rod, Stainless Steel Piston Rod & SS Tie Rods & Viton','DD':'Double Rod, Silent Seal Bumpers, Stainless Steel Piston Rod & SS Tie Rods',
'DE':'Double Rod, Silent Seal Bumpers, Stainless Steel Piston Rod & SS Tie Rods, & Metallic Rod Scraper','DF':'Double Rod and Bumper (Head End Only)',
'DG':'Double Rod and Bumpers (Head and Cap) & Metallic Rod Scraper','DH':'Double Rod and Bumpers (Head and Cap) & Viton Seals',
'DI':'Double Rod and Bumpers (Head and Cap), Metallic Rod Scraper & Viton Seals','DJ':'Double Rod, Stainless Steel Piston Rod & SS Tie Rods, Viton & Metallic Rod Scraper',
'DM':'Double Rod & Male Rod Stud','DN':'Double Rod and Male Rod Stud (Cap End Only)','DO':'Double Rod and Male Rod Stud (Head and Cap End)',
'DP':'Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod & SS Tie Rods, & Viton Seals','DQ':'Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod & SS Tie Rods, Viton Seals & Metallic Rod Scraper',
'DR':'Double Rod','DS':'Double Rod & Stainless Steel Piston Rod','DT':'Double Rod & Stainless Steel Tie Rods','DU':'Double Rod, Stainless Steel Piston Rod, & Stainless Steel Tie Rods',
'DW':'Double Rod & Metallic Rod Scraper','DX':'Double Rod and Male Rod Stud (Head and Cap End) & Metallic Rod Scraper','DY':'Double Rod and Male Rod Stud (Head and Cap End) & Viton Seals',
'DZ':'Double Rod, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper','ED':'Double Rod & Silent Seal Bumpers',
'EE':'Silent Seal Bumpers, Double Rod & Stainless Steel Piston Rod & Metallic Rod Scraper','EF':'Double Rod, Male Rod and Stainless Steel Piston Rods & Tie Rods',
'EG':'Silent Seal Bumpers, Double Rod, Male Rod & Metallic Rod Scraper','EH':'Silent Seal Bumpers, Double Rod, Male Rod, Stainless Steel Piston Rods & Tie Rods & Metallic Rod Scraper',
'EI':'Silent Seal Bumpers, Double Rod, Male Rod, Stainless Steel Piston Rods & Metallic Rod Scraper','EJ':'Silent Seal Bumpers, Male Rod, Stainless Steel Piston Rods & Tie Rods & Metallic Rod Scraper',
'EK':'Silent Seal Bumpers, Stainless Steel Piston Rods & Tie Rods & Metallic Rod Scraper','EM':'Male Rod and Silent Seal Bumpers',
'EN':'Male Rod, Double Rod and Silent Seal Bumpers','EO':'Male Rod, Silent Seal Bumpers & Metallic Rod Scraper','EP':'Silent Seal Bumpers and PolyPak Rod Seal',
'ER':'Silent Seal Bumpers and Stainless Steel Piston Rod','ES':'Silent Seal Bumpers and Stainless Rod and Stainless Tie Rods',
'ET':'Silent Seal Bumpers and Stainless Steel Tie Rods','EU':'Silent Seal Bumpers and Stainless Steel Piston Rods & Tie Rods and Male Rod',
'EW':'Silent Seal Bumpers and Metallic Rod Scraper','EZ':'Silent Seal Bumpers and Stainless Rod and Stainless Tie Rods and SuperLube',
'FB':'Bumper Front & Bumper Rear and SuperLube','HA':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods',
'HB':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'HC':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Viton Seals',
'HD':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'HE':'Low Breakaway, Double Rod, Stainless Steel Piston Rod, Stainless Steel Tie Rods','HF':'Low Breakaway, Double Rod, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'HG':'Low Breakaway, Double Rod, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Viton Seals','HH':'Low Breakaway, Double Rod, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'HI':'Low Breakaway, Double Rod, Bumpers (Head and Cap)','HJ':'Low Breakaway, Double Rod, Bumpers (Head and Cap) & Metallic Rod Scraper',
'HK':'Low Breakaway, Double Rod, Bumpers (Head and Cap) & Viton Seals','HL':'Low Breakaway, Double Rod, Bumpers (Head and Cap), Viton Seals & Metallic Rod Scraper',
'HM':'Low Breakaway, Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod, Stainless Steel Tie Rods',
'HN':'Low Breakaway, Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'HO':'Low Breakaway, Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod, Stainless Steel Tie Rods & Viton Seals',
'HP':'Low Breakaway, Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'HQ':'Low Breakaway, Double Rod, Male Rod Stud','HR':'Low Breakaway, Double Rod, Male Rod Stud & Metallic Rod Scraper',
'HS':'Low Breakaway, Double Rod, Male Rod Stud & Viton Seals','HT':'Low Breakaway, Double Rod, Male Rod Stud, Viton Seals & Metallic Rod Scraper',
'HU':'Low Breakaway, Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods','HV':'Low Breakaway, Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'HW':'Low Breakaway, Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Viton Seals','HX':'Low Breakaway, Double Rod, Male Rod Stud, Viton Seals, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'HY':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud','HZ':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud & Metallic Rod Scraper',
'IA':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud & Viton Seals','IB':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud, Viton Seals & Metallic Rod Scraper',
'IC':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods',
'ID':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'IE':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Viton Seals',
'IF':'Low Breakaway, Bumpers (Head and Cap), Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'IG':'Low Breakaway and Double Rod','IH':'Low Breakaway, Double Rod, Viton Seals','LA':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper',
'LB':'Low Breakaway (Piston Seals)','LC':'Low Breakaway, Bumpers (Head and Cap) & Metallic Rod Scraper','LD':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Bumpers (Head and Cap)',
'LE':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Bumpers (Head and Cap) & Metallic Rod Scraper',
'LF':'Metallic Rod Scraper and Low Breakaway and Viton','LG':'Double Rod and Metallic Rod Scraper and Low Breakaway and Viton',
'LH':'Low Breakaway, Male Rod Stud & Metallic Rod Scraper','LI':'Low Breakaway, Male Rod Stud & Viton Seals','LJ':'Low Breakaway, Male Rod Stud, Viton Seals & Metallic Rod Scraper',
'LK':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Male Rod Stud','LL':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Male Rod Stud & Metallic Rod Scraper',
'LM':'Male Rod and  and Low Breakaway','LN':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Male Rod Stud & Viton Seals',
'LO':'Low Breakaway, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Male Rod Stud, Viton Seals & Metallic Rod Scraper',
'LQ':'Low Breakaway and Stainless Tie Rods','LR':'Stainless Steel Piston Rod and Low Breakaway','LS':'Low Breakaway and Stainless Rod and Stainless Tie Rods',
'LU':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud','LV':'Low Breakaway & Viton','LW':'Low Breakaway and Metallic Rod Scraper',
'LX':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud & Metallic Rod Scraper','LY':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud & Viton Seals',
'LZ':'Low Breakaway, Bumpers (Head and Cap), Male Rod Stud, Viton Seals & Metallic Rod Scraper','MB':'Bumpers Head and Cap & Metallic Rod Scraper',
'MC':'Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods','MD':'Male Rod Stud & Stainless Steel Piston Rod',
'ME':'Double Rod, Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper','MF':'Double Rod, Bumpers (Head and Cap) & Male Rod Stud',
'MH':'Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod & SS Tie Rods, Male Rod Stud','MI':'Double Rod, Bumpers (Head and Cap), Stainless Steel Piston Rod & SS Tie Rods, Male Rod Stud & Metallic Rod Scraper',
'MJ':'Double Rod, Stainless Steel Piston Rod & SS Tie Rods, Male Rod Stud & Viton Seals','MK':'Male Rod Stud & Stainless Steel Tie Rods',
'MP':'PolyPak Rod Seal & Metallic Rod Scraper','MQ':'Male Rod Stud, Stainless Steel Piston Rod, & Viton Seals','MR':'Male Rod Stud',
'MS':'Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper','PA':'PolyPak Rod Seal','PB':'PolyPak Rod Seal & Bumpers, Head and Cap',
'PC':'Stainless Rod and PolyPak Rod Seal & PolyPak Piston Seals','PD':'Double Rod and PolyPak Rod Seal and Viton','PE':'Stainless Rod and PolyPak Rod Seal',
'PF':'Stainless Rod and PolyPak Piston Seals','PG':'PolyPak Rod Seal & PolyPak Piston Seals and Bumpers, Head and Cap','PH':'PolyPak Rod Seal, Stainless Steel Tie Rods and Metallic Rod Scraper',
'PI':'Stainless Steel Piston Rod & Stainless Steel Tie Rods and Metallic Rod Scraper','PM':'Male Rod Stud & PolyPak Rod Seal',
'PN':'Double Rod and PolyPak Rod Seal and PolyPak Piston Seals and Viton','PP':'PolyPak Piston Seals','PQ':'PolyPak Rod Seal & PolyPak Piston Seals',
'PR':'Double Rod and Metallic Rod Scraper and PolyPak Rod Seal and Silent Seal Bumpers','PS':'Stainless Rod and Stainless Tie Rods and PolyPak Rod Seal',
'PT':'Stainless Steel Tie Rods and PolyPak Rod Seal ','PU':'PolyPak Rod Seal and Viton','PV':'PolyPak Rod Seal, PolyPak Piston Seals & Viton',
'PW':'Double Rod and Metallic Rod Scraper and Silent Seal Bumpers','PX':'PolyPak Piston Seals & Viton','PY':'PolyPak Rod Seal and Double Rod and Silent Seal Bumpers',
'PZ':'Double Rod and PolyPak Piston Seals and Viton',
'RW':'Composite Tubing, Silent Seal Bumpers, Stainless Rod and Stainless Tie Rods, Hard Anodized Head, Cap & Rod Bearing* Model should include Fixed Cushions (Y) & Magnet options (E)   Specifically for Schneider Packaging',
'SB':'Silent Seal Bumpers','SJ':'Bumper Rear and Stainless Steel Tie Rods','SK':'Bumpers, Head and Cap and Stainless Steel Piston Rod',
'SL':'Bumpers, Head and Cap, Male Rod and Stainless Steel Piston Rod','SM':'Stainless Steel Tie Rods and Male Rod','SO':'Stainless Steel Tie Rods and Viton',
'SP':'Bumper (Rod End Only), Double Rod, Stainless Steel Piston Rod & Stainless Steel Tie Rods','SQ':'Bumpers, Head and Cap & Stainless Rod and Stainless Tie Rods and Viton',
'SR':'Stainless Steel Piston Rod', 'SS':'Stainless Steel Piston Rod & Stainless Steel Tie Rods','ST':'Stainless Steel Tie Rods',
'SU':'Stainless Steel Piston Rod, Stainless Steel Tie Rods, & SuperLube','SV':'Stainless Steel Piston Rod, Stainless Steel Tie Rods, & Viton',
'SW':'Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton, SuperLube & Metallic Rod Scraper','SX':'Bumper Cap End Only, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Low Breakaway',
'SY':'Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton, and SuperLube','SZ':'SuperLube Grease','VB':'Male Rod Stud & Viton Seals & Metallic Rod Scraper',
'VC':'Male Rod Stud, Stainless Steel Piston Rod & Stainless Steel Tie Rods & Viton Seals','VD':'Bumper Front, Bumper Rear, Male Rod Stud, & Viton Seals',
'VE':'Male Rod Stud, Stainless Steel Piston Rod & Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper','VF':'Double Rod, Male Rod Stud, Viton Seals & Metallic Rod Scraper',
'VG':'Double Rod, Male Rod Stud, Stainless Steel Piston Rod & Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'VH':'Bumpers, Head and Cap, Double Rod, Male Rod Stud & Viton Seals','VI':'Bumpers, Head and Cap, Double Rod, Male Rod Stud & Viton Seals & Metallic Rod Scraper',
'VJ':'Bumpers, Head and Cap, Double Rod, Male Rod Stud, Stainless Steel Piston Rod & Stainless Steel Tie Rods & Viton Seals',
'VK':'Bumpers, Head and Cap, Double Rod, Male Rod Stud, Stainless Steel Piston Rod & Stainless Steel Tie Rods, Viton Seals & Metallic Rod Scraper',
'VL':'Low Breakaway and Stainless Rod and Stainless Tie Rods & Viton Seals','VM':'Male Rod Stud & Viton Seals',
'VN':'Low Breakaway and Stainless Rod and Stainless Tie Rods, Viton Seals & Metallic Rod Scraper','VO':'Low Breakaway, Bumper Front, Bumper Rear & Viton Seals',
'VP':'Low Breakaway, Bumper Front, Bumper Rear, Viton Seals & Metallic Rod Scraper','VQ':'Low Breakaway, Bumper Front, Bumper Rear, Stainless Rod and Stainless Tie Rods, Viton Seals',
'VR':'Stainless Steel Piston Rod & Viton Seals','VS':'Viton Seals','VT':'Low Breakaway, Bumper Front, Bumper Rear, Stainless Rod and Stainless Tie Rods, Viton Seals & Metallic Rod Scraper',
'VU':'Double Rod, Stainless Steel Piston Rod & Viton Seals','WB':'Bumpers, Head and Cap, Metallic Rod Scraper, PolyPak Rod Seal & PolyPak Piston Seals',
'WC':'Male Rod Stud, Stainless Steel Piston Rod, Stainless Steel Tie Rods & Metallic Rod Scraper','WD':'Composite Cylinder Tube, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Metallic Rod Scraper',
'WE':'Composite Cylinder Tube, Stainless Steel Piston Rod, Stainless Steel Tie Rods, Viton Seals, Metallic Rod Scraper',
'WF':'Double Rod and Metallic Rod Scraper and Silent Seal Bumpers','WG':'Metallic Rod Scraper and PolyPak Piston Seals and Viton',
'WH':'Double Rod and Metallic Rod Scraper and PolyPak Piston Seals and Viton','WJ':'Double Rod and Metallic Rod Scraper and PolyPak Piston Seals',
'WK':'Metallic Rod Scraper and PolyPak Piston Seals','WL':'Double Rod and Metallic Rod Scraper and Low Breakaway','WM':'Male Rod & Metallic Rod Scraper',
'WN':'Double Rod and Metallic Rod Scraper and PolyPak Rod Seal & PolyPak Piston Seals and Viton','WO':'Double Rod and Metallic Rod Scraper and PolyPak Rod Seal',
'WP':'Metallic Rod Scraper and PolyPak Rod Seal','WQ':'Metallic Rod Scraper and PolyPak Rod Seal & PolyPak Piston Seals','WR':'Stainless Steel Piston Rod & Metallic Rod Scraper',
'WS':'Metallic Rod Scraper','WT':'Double Rod and Metallic Rod Scraper and Viton','WU':'Metallic Rod Scraper and PolyPak Rod Seal and Viton',
'WV':'Viton & Metallic Rod Scraper','WW':'Metallic Rod Scraper and PolyPak Rod Seal & PolyPak Piston Seals and Viton','WX':'Double Rod and Metallic Rod Scraper and PolyPak Rod Seal & PolyPak Piston Seals',
'WY':'Double Rod and Metallic Rod Scraper and PolyPak Rod Seal and Viton','WZ':'Metallic Rod Scraper and PolyPak Rod Seal and Silent Seal Bumpers',
'XX':'No Options'}

option_addition = {
    "AH": "SR+ST+VS+WS",
    "BB": "BF+BR",
    "BD": "BF+BR+VS+WS",
    "BE": "BF+BR+SR+ST+WS",
    "BF": "BF",
    "BG": "BF+BR+SR+ST+VS+WS",
    "BI": "BF+BR+MR+WS",
    "BJ": "BF+BR+MR+VS+WS",
    "BL": "BF+BR+LB",
    "BM": "BF+BR+MR",
    "BN": "BF+BR+MR+SR+ST",
    "BO": "BF+BR+MR+SR+ST+WS",
    "BP": "BF+BR+PA",
    "BQ": "BF+BR+MR+SR+ST+VS",
    "BR": "BR",
    "BS": "BF+BR+SR+ST",
    "BT": "BF+BR+ST",
    "BU": "BF+BR+MR+SR+ST+VS+WS",
    "BV": "BF+BR+VS",
    "BW": "BF+BR+WS",
    "CD": "DR+BR",
    "CE": "CT+SB",
    "CR": "CT+SR",
    "CS": "CT+ST",
    "CT": "CT",
    "CU": "CT+SR+ST",
    "DB": "DR+BF+BR",
    "DC": "DR+SR+ST+VS",
    "DD": "DR+SB+SR+ST",
    "DE": "DR+SB+SR+ST+WS",
    "DF": "DR+BF",
    "DG": "DR+BF+BR+WS",
    "DH": "DR+BF+BR+VS",
    "DI": "DR+BF+BR+VS+WS",
    "DJ": "DR+SR+ST+VS+WS",
    "DK": "DR+BF+BR+SR+ST",
    "DL": "DR+BF+BR+SR+ST+WS",
    "DM": "DR+MR (Front)",
    "DN": "DR+MR (Rear)",
    "DO": "DR+MR (Front & Rear)",
    "DP": "DR+BF+BR+SR+ST+VS",
    "DQ": "DR+BF+BR+SR+ST+VS+WS",
    "DR": "Double Rod",
    "DS": "DR+SR",
    "DT": "DR+ST",
    "DU": "DR+SR+ST",
    "DV": "DR+VS",
    "DW": "DR+WS",
    "DX": "DR+WS+MR (Front & Rear)",
    "DY": "DR+VS+MR (Front & Rear)",
    "DZ": "DR+SR+ST+WS",
    "ED": "DR+SB",
    "EE": "SB+DR+SR+WS",
    "EF": "DR+MR+SR+ST+WS",
    "EG": "SB+DR+MR+WS",
    "EH": "SB+DR+MR+SR+ST",
    "EI": "SB+DR+MR+SR+ST+WS",
    "EJ": "SB+MR+SR+ST+WS",
    "EK": "SB+SR+ST+WS",
    "EM": "SB+MR",
    "EN": "SB+DR+MR",
    "EO": "SB+MR+WS",
    "EP": "SB+PA",
    "ER": "SB+SR",
    "ES": "SB+SR+ST",
    "ET": "SB+ST",
    "EU": "SB+SS+MR",
    "EW": "SB+WS",
    "EZ": "SB+SR+ST+SZ",
    "FB": "BF+BR+SZ",
    "HA": "LB+MR+BF+BR+SR+ST",
    "HB": "LB+MR+BF+BR+SR+ST+WS",
    "HC": "LB+MR+BF+BR+SR+ST+VS",
    "HD": "LB+MR+BF+BR+SR+ST+VS+WS",
    "HE": "LB+DR+SR+ST",
    "HF": "LB+DR+SR+ST+WS",
    "HG": "LB+DR+SR+ST+VS",
    "HH": "LB+DR+SR+ST+VS+WS",
    "HI": "LB+DR+BF+BR",
    "HJ": "LB+DR+BF+BR+WS",
    "HK": "LB+DR+BF+BR+VS",
    "HL": "LB+DR+BF+BR+VS+WS",
    "HM": "LB+DR+BF+BR+SR+ST",
    "HN": "LB+DR+BF+BR+SR+ST+WS",
    "HO": "LB+DR+BF+BR+SR+ST+VS",
    "HP": "LB+DR+BF+BR+SR+ST+VS+WS",
    "HQ": "LB+DR+MR",
    "HR": "LB+DR+MR+WS",
    "HS": "LB+DR+MR+VS",
    "HT": "LB+DR+MR+VS+WS",
    "HU": "LB+DR+MR+SR+ST",
    "HV": "LB+DR+MR+SR+ST+WS",
    "HW": "LB+DR+MR+SR+ST+VS",
    "HX": "LB+DR+MR+SR+ST+VS+WS",
    "HY": "LB+BF+BR+DR+MR",
    "HZ": "LB+BF+BR+DR+MR+WS",
    "IA": "LB+BF+BR+DR+MR+VS",
    "IB": "LB+BF+BR+DR+MR+VS+WS",
    "IC": "LB+BF+BR+DR+MR+SR+ST",
    "ID": "LB+BF+BR+DR+MR+SR+ST+WS",
    "IE": "LB+BF+BR+DR+MR+SR+ST+VS",
    "IF": "LB+BF+BR+DR+MR+SR+ST+VS+WS",
    "IG": "LB+DR",
    "IH": "LB+DR+VS",
    "LA": "LB+SR+ST+WS",
    "LB": "LB",
    "LC": "LB+BF+BR+WS",
    "LD": "LB+BF+BR+SR+ST",
    "LE": "LB+BF+BR+SR+ST+WS",
    "LF": "LB+VS+WS",
    "LG": "LB+DR+VS+WS",
    "LH": "LB+MR+WS",
    "LI": "LB+MR+VS",
    "LJ": "LB+MR+VS+WS",
    "LK": "LB+MR+SR+ST",
    "LL": "LB+MR+SR+ST+WS",
    "LM": "LB+MR",
    "LN": "LB+MR+SR+ST+VS",
    "LO": "LB+MR+SR+ST+VS+WS",
    "LQ": "LB+ST",
    "LR": "LB+SR",
    "LS": "LB+SS",
    "LU": "LB+MR+BF+BR",
    "LV": "LB+VS",
    "LW": "LB+WS",
    "LX": "LB+MR+BF+BR+WS",
    "LY": "LB+MR+BF+BR+VS",
    "LZ": "LB+MR+BF+BR+VS+WS",
    "MB": "WS+BB",
    "MC": "MR+SR+ST",
    "MD": "MR+SR",
    "ME": "DR+MR+SR+ST+WS",
    "MF": "DR+MR+BF+BR",
    "MG": "DR+MR+BF+BR+WS",
    "MH": "DR+MR+BF+BR+SR+ST",
    "MI": "DR+MR+BF+BR+SR+ST+WS",
    "MJ": "DR+MR+SR+ST+VS",
    "MK": "MR+ST",
    "MP": "PA+WS",
    "MQ": "MR+SR+VS",
    "MR": "MR",
    "MS": "SR+ST+WS",
    "PA": "PA",
    "PB": "PA + BB",
    "PC": "PA+PP+SR",
    "PD": "PA+DR+V",
    "PE": "PA+SR",
    "PF": "PP+SR",
    "PG": "PA+PP+BB",
    "PH": "PA+ST+WS",
    "PI": "PA+SS+WS",
    "PM": "MR+PA",
    "PN": "PA+PP+DR+V",
    "PP": "PP",
    "PQ": "PA+PP",
    "PR": "PA+DR+SB+WS",
    "PS": "PA+SS",
    "PT": "PA+ST",
    "PU": "PA+VS",
    "PV": "PA+PP+VS",
    "PW": "PA+WS",
    "PX": "PP+VS",
    "PY": "PA+DR+SB",
    "PZ": "PP+DR+V",
    "RW": "CT+SB+SR+ST",
    "SB": "SB",
    "SJ": "BR + ST",
    "SK": "BF+BR+SR",
    "SL": "BF+BR+MR+SR",
    "SM": "ST+MR",
    "SO": "ST+VS",
    "SP": "BF+DR+SR+ST",
    "SQ": "SR+ST+BF+BR+VS",
    "SR": "SR",
    "SS": "SR+ST",
    "ST": "ST",
    "SU": "SR+ST+SZ",
    "SV": "SR+ST+VS",
    "SW": "SR+ST+VS+SZ+WS",
    "SX": "SR+ST+BR+LB",
    "SY": "SR+ST+VS+SZ",
    "SZ": "SZ",
    "VB": "MR+VS+WS",
    "VC": "MR+SR+ST+VS",
    "VD": "BF+BR+MR+VS",
    "VE": "MR+SR+ST+VS+WS",
    "VF": "DR+MR+VS+WS",
    "VG": "DR+MR+SR+ST+VS+WS",
    "VH": "BF+BR+DR+MR+VS",
    "VI": "BF+BR+DR+MR+VS+WS",
    "VJ": "BF+BR+DR+MR+SR+ST+VS",
    "VK": "BF+BR+DR+MR+SR+ST+VS+WS",
    "VL": "LB+SS+VS",
    "VM": "MR+VS",
    "VN": "LB+SS+VS+WS",
    "VO": "LB+BF+BR+VS",
    "VP": "LB+BF+BR+VS+WS",
    "VQ": "LB+BF+BR+SR+ST+VS",
    "VR": "SR+VS",
    "VS": "VS",
    "VT": "LB+BF+BR+SR+ST+VS+WS",
    "VU": "DR+SR+VS",
    "WB": "BF+BR+PA+PP+WS",
    "WC": "MR+SR+ST+WS",
    "WD": "CT+SR+ST+WS",
    "WE": "CT+SR+ST+VS+WS",
    "WF": "WS+DR+SB",
    "WG": "WS+PP+VS",
    "WH": "WS+DR+PP+VS",
    "WJ": "WS+DR+PP",
    "WK": "WS+PP",
    "WL": "WS+DR+LB",
    "WM": "MR+WS",
    "WN": "WS+DR+PA+PP+VS",
    "WO": "WS+DR+PA",
    "WP": "WS+PA",
    "WQ": "WS+PA+PP",
    "WR": "SR+WS",
    "WS": "WS",
    "WT": "WS+DR+VS",
    "WU": "WS+PA+VS",
    "WV": "VS+WS",
    "WW": "WS+PA+PP+VS",
    "WX": "WS+DR+PA+PP",
    "WY": "WS+DR+PA+VS",
    "WZ": "WS+PA+SB",
    "XX": "XX"
}
